// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: authzed/api/v1/core.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Authzed.Api.V1 {

  /// <summary>Holder for reflection information generated from authzed/api/v1/core.proto</summary>
  public static partial class CoreReflection {

    #region Descriptor
    /// <summary>File descriptor for authzed/api/v1/core.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CoreReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlhdXRoemVkL2FwaS92MS9jb3JlLnByb3RvEg5hdXRoemVkLmFwaS52MRoX",
            "dmFsaWRhdGUvdmFsaWRhdGUucHJvdG8i4AEKDFJlbGF0aW9uc2hpcBJFCghy",
            "ZXNvdXJjZRgBIAEoCzIfLmF1dGh6ZWQuYXBpLnYxLk9iamVjdFJlZmVyZW5j",
            "ZUII+kIFigECEAFSCHJlc291cmNlEkMKCHJlbGF0aW9uGAIgASgJQif6QiRy",
            "IihAMh5eW2Etel1bYS16MC05X117Miw2Mn1bYS16MC05XSRSCHJlbGF0aW9u",
            "EkQKB3N1YmplY3QYAyABKAsyIC5hdXRoemVkLmFwaS52MS5TdWJqZWN0UmVm",
            "ZXJlbmNlQgj6QgWKAQIQAVIHc3ViamVjdCKkAQoQU3ViamVjdFJlZmVyZW5j",
            "ZRI3CgZvYmplY3QYASABKAsyHy5hdXRoemVkLmFwaS52MS5PYmplY3RSZWZl",
            "cmVuY2VSBm9iamVjdBJXChFvcHRpb25hbF9yZWxhdGlvbhgCIAEoCUIq+kIn",
            "ciUoQDIhXihbYS16XVthLXowLTlfXXsyLDYyfVthLXowLTldKT8kUhBvcHRp",
            "b25hbFJlbGF0aW9uIsgBCg9PYmplY3RSZWZlcmVuY2USaQoLb2JqZWN0X3R5",
            "cGUYASABKAlCSPpCRXJDKIABMj5eKFthLXpdW2EtejAtOV9dezIsNjF9W2Et",
            "ejAtOV0vKT9bYS16XVthLXowLTlfXXsyLDYyfVthLXowLTldJFIKb2JqZWN0",
            "VHlwZRJKCglvYmplY3RfaWQYAiABKAlCLfpCKnIoKIABMiNeW2EtekEtWjAt",
            "OV9dW2EtekEtWjAtOS9fLV17MCwxMjd9JFIIb2JqZWN0SWQiKQoIWmVkVG9r",
            "ZW4SHQoFdG9rZW4YASABKAlCB/pCBHICIAFSBXRva2VuIp8CChJSZWxhdGlv",
            "bnNoaXBVcGRhdGUSVAoJb3BlcmF0aW9uGAEgASgOMiwuYXV0aHplZC5hcGku",
            "djEuUmVsYXRpb25zaGlwVXBkYXRlLk9wZXJhdGlvbkII+kIFggECEAFSCW9w",
            "ZXJhdGlvbhJKCgxyZWxhdGlvbnNoaXAYAiABKAsyHC5hdXRoemVkLmFwaS52",
            "MS5SZWxhdGlvbnNoaXBCCPpCBYoBAhABUgxyZWxhdGlvbnNoaXAiZwoJT3Bl",
            "cmF0aW9uEhkKFU9QRVJBVElPTl9VTlNQRUNJRklFRBAAEhQKEE9QRVJBVElP",
            "Tl9DUkVBVEUQARITCg9PUEVSQVRJT05fVE9VQ0gQAhIUChBPUEVSQVRJT05f",
            "REVMRVRFEAMiqAIKGlBlcm1pc3Npb25SZWxhdGlvbnNoaXBUcmVlEkkKDGlu",
            "dGVybWVkaWF0ZRgBIAEoCzIjLmF1dGh6ZWQuYXBpLnYxLkFsZ2VicmFpY1N1",
            "YmplY3RTZXRIAFIMaW50ZXJtZWRpYXRlEjYKBGxlYWYYAiABKAsyIC5hdXRo",
            "emVkLmFwaS52MS5EaXJlY3RTdWJqZWN0U2V0SABSBGxlYWYSSAoPZXhwYW5k",
            "ZWRfb2JqZWN0GAMgASgLMh8uYXV0aHplZC5hcGkudjEuT2JqZWN0UmVmZXJl",
            "bmNlUg5leHBhbmRlZE9iamVjdBIrChFleHBhbmRlZF9yZWxhdGlvbhgEIAEo",
            "CVIQZXhwYW5kZWRSZWxhdGlvbkIQCgl0cmVlX3R5cGUSA/hCASKcAgoTQWxn",
            "ZWJyYWljU3ViamVjdFNldBJLCglvcGVyYXRpb24YASABKA4yLS5hdXRoemVk",
            "LmFwaS52MS5BbGdlYnJhaWNTdWJqZWN0U2V0Lk9wZXJhdGlvblIJb3BlcmF0",
            "aW9uEkYKCGNoaWxkcmVuGAIgAygLMiouYXV0aHplZC5hcGkudjEuUGVybWlz",
            "c2lvblJlbGF0aW9uc2hpcFRyZWVSCGNoaWxkcmVuInAKCU9wZXJhdGlvbhIZ",
            "ChVPUEVSQVRJT05fVU5TUEVDSUZJRUQQABITCg9PUEVSQVRJT05fVU5JT04Q",
            "ARIaChZPUEVSQVRJT05fSU5URVJTRUNUSU9OEAISFwoTT1BFUkFUSU9OX0VY",
            "Q0xVU0lPThADIlAKEERpcmVjdFN1YmplY3RTZXQSPAoIc3ViamVjdHMYASAD",
            "KAsyIC5hdXRoemVkLmFwaS52MS5TdWJqZWN0UmVmZXJlbmNlUghzdWJqZWN0",
            "c0JIChJjb20uYXV0aHplZC5hcGkudjFaMmdpdGh1Yi5jb20vYXV0aHplZC9h",
            "dXRoemVkLWdvL3Byb3RvL2F1dGh6ZWQvYXBpL3YxYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Validate.ValidateReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Authzed.Api.V1.Relationship), global::Authzed.Api.V1.Relationship.Parser, new[]{ "Resource", "Relation", "Subject" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Authzed.Api.V1.SubjectReference), global::Authzed.Api.V1.SubjectReference.Parser, new[]{ "Object", "OptionalRelation" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Authzed.Api.V1.ObjectReference), global::Authzed.Api.V1.ObjectReference.Parser, new[]{ "ObjectType", "ObjectId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Authzed.Api.V1.ZedToken), global::Authzed.Api.V1.ZedToken.Parser, new[]{ "Token" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Authzed.Api.V1.RelationshipUpdate), global::Authzed.Api.V1.RelationshipUpdate.Parser, new[]{ "Operation", "Relationship" }, null, new[]{ typeof(global::Authzed.Api.V1.RelationshipUpdate.Types.Operation) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Authzed.Api.V1.PermissionRelationshipTree), global::Authzed.Api.V1.PermissionRelationshipTree.Parser, new[]{ "Intermediate", "Leaf", "ExpandedObject", "ExpandedRelation" }, new[]{ "TreeType" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Authzed.Api.V1.AlgebraicSubjectSet), global::Authzed.Api.V1.AlgebraicSubjectSet.Parser, new[]{ "Operation", "Children" }, null, new[]{ typeof(global::Authzed.Api.V1.AlgebraicSubjectSet.Types.Operation) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Authzed.Api.V1.DirectSubjectSet), global::Authzed.Api.V1.DirectSubjectSet.Parser, new[]{ "Subjects" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Relationship specifies how a resource relates to a subject. Relationships
  /// form the data for the graph over which all permissions questions are
  /// answered.
  /// </summary>
  public sealed partial class Relationship : pb::IMessage<Relationship>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Relationship> _parser = new pb::MessageParser<Relationship>(() => new Relationship());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Relationship> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Authzed.Api.V1.CoreReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Relationship() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Relationship(Relationship other) : this() {
      resource_ = other.resource_ != null ? other.resource_.Clone() : null;
      relation_ = other.relation_;
      subject_ = other.subject_ != null ? other.subject_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Relationship Clone() {
      return new Relationship(this);
    }

    /// <summary>Field number for the "resource" field.</summary>
    public const int ResourceFieldNumber = 1;
    private global::Authzed.Api.V1.ObjectReference resource_;
    /// <summary>
    /// resource is the resource to which the subject is related, in some manner
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Authzed.Api.V1.ObjectReference Resource {
      get { return resource_; }
      set {
        resource_ = value;
      }
    }

    /// <summary>Field number for the "relation" field.</summary>
    public const int RelationFieldNumber = 2;
    private string relation_ = "";
    /// <summary>
    /// relation is how the resource and subject are related.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Relation {
      get { return relation_; }
      set {
        relation_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "subject" field.</summary>
    public const int SubjectFieldNumber = 3;
    private global::Authzed.Api.V1.SubjectReference subject_;
    /// <summary>
    /// subject is the subject to which the resource is related, in some manner.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Authzed.Api.V1.SubjectReference Subject {
      get { return subject_; }
      set {
        subject_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Relationship);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Relationship other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Resource, other.Resource)) return false;
      if (Relation != other.Relation) return false;
      if (!object.Equals(Subject, other.Subject)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (resource_ != null) hash ^= Resource.GetHashCode();
      if (Relation.Length != 0) hash ^= Relation.GetHashCode();
      if (subject_ != null) hash ^= Subject.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (resource_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Resource);
      }
      if (Relation.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Relation);
      }
      if (subject_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Subject);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (resource_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Resource);
      }
      if (Relation.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Relation);
      }
      if (subject_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Subject);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (resource_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Resource);
      }
      if (Relation.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Relation);
      }
      if (subject_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Subject);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Relationship other) {
      if (other == null) {
        return;
      }
      if (other.resource_ != null) {
        if (resource_ == null) {
          Resource = new global::Authzed.Api.V1.ObjectReference();
        }
        Resource.MergeFrom(other.Resource);
      }
      if (other.Relation.Length != 0) {
        Relation = other.Relation;
      }
      if (other.subject_ != null) {
        if (subject_ == null) {
          Subject = new global::Authzed.Api.V1.SubjectReference();
        }
        Subject.MergeFrom(other.Subject);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (resource_ == null) {
              Resource = new global::Authzed.Api.V1.ObjectReference();
            }
            input.ReadMessage(Resource);
            break;
          }
          case 18: {
            Relation = input.ReadString();
            break;
          }
          case 26: {
            if (subject_ == null) {
              Subject = new global::Authzed.Api.V1.SubjectReference();
            }
            input.ReadMessage(Subject);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (resource_ == null) {
              Resource = new global::Authzed.Api.V1.ObjectReference();
            }
            input.ReadMessage(Resource);
            break;
          }
          case 18: {
            Relation = input.ReadString();
            break;
          }
          case 26: {
            if (subject_ == null) {
              Subject = new global::Authzed.Api.V1.SubjectReference();
            }
            input.ReadMessage(Subject);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// SubjectReference is used for referring to the subject portion of a
  /// Relationship. The relation component is optional and is used for defining a
  /// sub-relation on the subject, e.g. group:123#members
  /// </summary>
  public sealed partial class SubjectReference : pb::IMessage<SubjectReference>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SubjectReference> _parser = new pb::MessageParser<SubjectReference>(() => new SubjectReference());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SubjectReference> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Authzed.Api.V1.CoreReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SubjectReference() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SubjectReference(SubjectReference other) : this() {
      object_ = other.object_ != null ? other.object_.Clone() : null;
      optionalRelation_ = other.optionalRelation_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SubjectReference Clone() {
      return new SubjectReference(this);
    }

    /// <summary>Field number for the "object" field.</summary>
    public const int ObjectFieldNumber = 1;
    private global::Authzed.Api.V1.ObjectReference object_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Authzed.Api.V1.ObjectReference Object {
      get { return object_; }
      set {
        object_ = value;
      }
    }

    /// <summary>Field number for the "optional_relation" field.</summary>
    public const int OptionalRelationFieldNumber = 2;
    private string optionalRelation_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OptionalRelation {
      get { return optionalRelation_; }
      set {
        optionalRelation_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SubjectReference);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SubjectReference other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Object, other.Object)) return false;
      if (OptionalRelation != other.OptionalRelation) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (object_ != null) hash ^= Object.GetHashCode();
      if (OptionalRelation.Length != 0) hash ^= OptionalRelation.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (object_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Object);
      }
      if (OptionalRelation.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(OptionalRelation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (object_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Object);
      }
      if (OptionalRelation.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(OptionalRelation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (object_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Object);
      }
      if (OptionalRelation.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OptionalRelation);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SubjectReference other) {
      if (other == null) {
        return;
      }
      if (other.object_ != null) {
        if (object_ == null) {
          Object = new global::Authzed.Api.V1.ObjectReference();
        }
        Object.MergeFrom(other.Object);
      }
      if (other.OptionalRelation.Length != 0) {
        OptionalRelation = other.OptionalRelation;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (object_ == null) {
              Object = new global::Authzed.Api.V1.ObjectReference();
            }
            input.ReadMessage(Object);
            break;
          }
          case 18: {
            OptionalRelation = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (object_ == null) {
              Object = new global::Authzed.Api.V1.ObjectReference();
            }
            input.ReadMessage(Object);
            break;
          }
          case 18: {
            OptionalRelation = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// ObjectReference is used to refer to a specific object in the system.
  /// </summary>
  public sealed partial class ObjectReference : pb::IMessage<ObjectReference>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ObjectReference> _parser = new pb::MessageParser<ObjectReference>(() => new ObjectReference());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ObjectReference> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Authzed.Api.V1.CoreReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ObjectReference() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ObjectReference(ObjectReference other) : this() {
      objectType_ = other.objectType_;
      objectId_ = other.objectId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ObjectReference Clone() {
      return new ObjectReference(this);
    }

    /// <summary>Field number for the "object_type" field.</summary>
    public const int ObjectTypeFieldNumber = 1;
    private string objectType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ObjectType {
      get { return objectType_; }
      set {
        objectType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "object_id" field.</summary>
    public const int ObjectIdFieldNumber = 2;
    private string objectId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ObjectId {
      get { return objectId_; }
      set {
        objectId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ObjectReference);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ObjectReference other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ObjectType != other.ObjectType) return false;
      if (ObjectId != other.ObjectId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ObjectType.Length != 0) hash ^= ObjectType.GetHashCode();
      if (ObjectId.Length != 0) hash ^= ObjectId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ObjectType.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ObjectType);
      }
      if (ObjectId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ObjectId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ObjectType.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ObjectType);
      }
      if (ObjectId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ObjectId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ObjectType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ObjectType);
      }
      if (ObjectId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ObjectId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ObjectReference other) {
      if (other == null) {
        return;
      }
      if (other.ObjectType.Length != 0) {
        ObjectType = other.ObjectType;
      }
      if (other.ObjectId.Length != 0) {
        ObjectId = other.ObjectId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ObjectType = input.ReadString();
            break;
          }
          case 18: {
            ObjectId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ObjectType = input.ReadString();
            break;
          }
          case 18: {
            ObjectId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// ZedToken is used to provide causality metadata between Write and Check
  /// requests.
  ///
  /// See the authzed.api.v1.Consistency message for more information.
  /// </summary>
  public sealed partial class ZedToken : pb::IMessage<ZedToken>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ZedToken> _parser = new pb::MessageParser<ZedToken>(() => new ZedToken());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ZedToken> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Authzed.Api.V1.CoreReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ZedToken() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ZedToken(ZedToken other) : this() {
      token_ = other.token_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ZedToken Clone() {
      return new ZedToken(this);
    }

    /// <summary>Field number for the "token" field.</summary>
    public const int TokenFieldNumber = 1;
    private string token_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Token {
      get { return token_; }
      set {
        token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ZedToken);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ZedToken other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Token != other.Token) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Token.Length != 0) hash ^= Token.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Token.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Token);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Token.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Token);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Token.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ZedToken other) {
      if (other == null) {
        return;
      }
      if (other.Token.Length != 0) {
        Token = other.Token;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Token = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Token = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// RelationshipUpdate is used for mutating a single relationship within the
  /// service.
  ///
  /// CREATE will create the relationship only if it doesn't exist, and error
  /// otherwise.
  ///
  /// TOUCH will upsert the relationship, and will not error if it
  /// already exists.
  ///
  /// DELETE will delete the relationship and error if it doesn't
  /// exist.
  /// </summary>
  public sealed partial class RelationshipUpdate : pb::IMessage<RelationshipUpdate>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RelationshipUpdate> _parser = new pb::MessageParser<RelationshipUpdate>(() => new RelationshipUpdate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RelationshipUpdate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Authzed.Api.V1.CoreReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RelationshipUpdate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RelationshipUpdate(RelationshipUpdate other) : this() {
      operation_ = other.operation_;
      relationship_ = other.relationship_ != null ? other.relationship_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RelationshipUpdate Clone() {
      return new RelationshipUpdate(this);
    }

    /// <summary>Field number for the "operation" field.</summary>
    public const int OperationFieldNumber = 1;
    private global::Authzed.Api.V1.RelationshipUpdate.Types.Operation operation_ = global::Authzed.Api.V1.RelationshipUpdate.Types.Operation.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Authzed.Api.V1.RelationshipUpdate.Types.Operation Operation {
      get { return operation_; }
      set {
        operation_ = value;
      }
    }

    /// <summary>Field number for the "relationship" field.</summary>
    public const int RelationshipFieldNumber = 2;
    private global::Authzed.Api.V1.Relationship relationship_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Authzed.Api.V1.Relationship Relationship {
      get { return relationship_; }
      set {
        relationship_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RelationshipUpdate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RelationshipUpdate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Operation != other.Operation) return false;
      if (!object.Equals(Relationship, other.Relationship)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Operation != global::Authzed.Api.V1.RelationshipUpdate.Types.Operation.Unspecified) hash ^= Operation.GetHashCode();
      if (relationship_ != null) hash ^= Relationship.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Operation != global::Authzed.Api.V1.RelationshipUpdate.Types.Operation.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Operation);
      }
      if (relationship_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Relationship);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Operation != global::Authzed.Api.V1.RelationshipUpdate.Types.Operation.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Operation);
      }
      if (relationship_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Relationship);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Operation != global::Authzed.Api.V1.RelationshipUpdate.Types.Operation.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Operation);
      }
      if (relationship_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Relationship);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RelationshipUpdate other) {
      if (other == null) {
        return;
      }
      if (other.Operation != global::Authzed.Api.V1.RelationshipUpdate.Types.Operation.Unspecified) {
        Operation = other.Operation;
      }
      if (other.relationship_ != null) {
        if (relationship_ == null) {
          Relationship = new global::Authzed.Api.V1.Relationship();
        }
        Relationship.MergeFrom(other.Relationship);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Operation = (global::Authzed.Api.V1.RelationshipUpdate.Types.Operation) input.ReadEnum();
            break;
          }
          case 18: {
            if (relationship_ == null) {
              Relationship = new global::Authzed.Api.V1.Relationship();
            }
            input.ReadMessage(Relationship);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Operation = (global::Authzed.Api.V1.RelationshipUpdate.Types.Operation) input.ReadEnum();
            break;
          }
          case 18: {
            if (relationship_ == null) {
              Relationship = new global::Authzed.Api.V1.Relationship();
            }
            input.ReadMessage(Relationship);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the RelationshipUpdate message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Operation {
        [pbr::OriginalName("OPERATION_UNSPECIFIED")] Unspecified = 0,
        [pbr::OriginalName("OPERATION_CREATE")] Create = 1,
        [pbr::OriginalName("OPERATION_TOUCH")] Touch = 2,
        [pbr::OriginalName("OPERATION_DELETE")] Delete = 3,
      }

    }
    #endregion

  }

  /// <summary>
  /// PermissionRelationshipTree is used for representing a tree of a resource and
  /// its permission relationships with other objects.
  /// </summary>
  public sealed partial class PermissionRelationshipTree : pb::IMessage<PermissionRelationshipTree>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PermissionRelationshipTree> _parser = new pb::MessageParser<PermissionRelationshipTree>(() => new PermissionRelationshipTree());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PermissionRelationshipTree> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Authzed.Api.V1.CoreReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PermissionRelationshipTree() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PermissionRelationshipTree(PermissionRelationshipTree other) : this() {
      expandedObject_ = other.expandedObject_ != null ? other.expandedObject_.Clone() : null;
      expandedRelation_ = other.expandedRelation_;
      switch (other.TreeTypeCase) {
        case TreeTypeOneofCase.Intermediate:
          Intermediate = other.Intermediate.Clone();
          break;
        case TreeTypeOneofCase.Leaf:
          Leaf = other.Leaf.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PermissionRelationshipTree Clone() {
      return new PermissionRelationshipTree(this);
    }

    /// <summary>Field number for the "intermediate" field.</summary>
    public const int IntermediateFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Authzed.Api.V1.AlgebraicSubjectSet Intermediate {
      get { return treeTypeCase_ == TreeTypeOneofCase.Intermediate ? (global::Authzed.Api.V1.AlgebraicSubjectSet) treeType_ : null; }
      set {
        treeType_ = value;
        treeTypeCase_ = value == null ? TreeTypeOneofCase.None : TreeTypeOneofCase.Intermediate;
      }
    }

    /// <summary>Field number for the "leaf" field.</summary>
    public const int LeafFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Authzed.Api.V1.DirectSubjectSet Leaf {
      get { return treeTypeCase_ == TreeTypeOneofCase.Leaf ? (global::Authzed.Api.V1.DirectSubjectSet) treeType_ : null; }
      set {
        treeType_ = value;
        treeTypeCase_ = value == null ? TreeTypeOneofCase.None : TreeTypeOneofCase.Leaf;
      }
    }

    /// <summary>Field number for the "expanded_object" field.</summary>
    public const int ExpandedObjectFieldNumber = 3;
    private global::Authzed.Api.V1.ObjectReference expandedObject_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Authzed.Api.V1.ObjectReference ExpandedObject {
      get { return expandedObject_; }
      set {
        expandedObject_ = value;
      }
    }

    /// <summary>Field number for the "expanded_relation" field.</summary>
    public const int ExpandedRelationFieldNumber = 4;
    private string expandedRelation_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ExpandedRelation {
      get { return expandedRelation_; }
      set {
        expandedRelation_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private object treeType_;
    /// <summary>Enum of possible cases for the "tree_type" oneof.</summary>
    public enum TreeTypeOneofCase {
      None = 0,
      Intermediate = 1,
      Leaf = 2,
    }
    private TreeTypeOneofCase treeTypeCase_ = TreeTypeOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TreeTypeOneofCase TreeTypeCase {
      get { return treeTypeCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTreeType() {
      treeTypeCase_ = TreeTypeOneofCase.None;
      treeType_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PermissionRelationshipTree);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PermissionRelationshipTree other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Intermediate, other.Intermediate)) return false;
      if (!object.Equals(Leaf, other.Leaf)) return false;
      if (!object.Equals(ExpandedObject, other.ExpandedObject)) return false;
      if (ExpandedRelation != other.ExpandedRelation) return false;
      if (TreeTypeCase != other.TreeTypeCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (treeTypeCase_ == TreeTypeOneofCase.Intermediate) hash ^= Intermediate.GetHashCode();
      if (treeTypeCase_ == TreeTypeOneofCase.Leaf) hash ^= Leaf.GetHashCode();
      if (expandedObject_ != null) hash ^= ExpandedObject.GetHashCode();
      if (ExpandedRelation.Length != 0) hash ^= ExpandedRelation.GetHashCode();
      hash ^= (int) treeTypeCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (treeTypeCase_ == TreeTypeOneofCase.Intermediate) {
        output.WriteRawTag(10);
        output.WriteMessage(Intermediate);
      }
      if (treeTypeCase_ == TreeTypeOneofCase.Leaf) {
        output.WriteRawTag(18);
        output.WriteMessage(Leaf);
      }
      if (expandedObject_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ExpandedObject);
      }
      if (ExpandedRelation.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ExpandedRelation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (treeTypeCase_ == TreeTypeOneofCase.Intermediate) {
        output.WriteRawTag(10);
        output.WriteMessage(Intermediate);
      }
      if (treeTypeCase_ == TreeTypeOneofCase.Leaf) {
        output.WriteRawTag(18);
        output.WriteMessage(Leaf);
      }
      if (expandedObject_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ExpandedObject);
      }
      if (ExpandedRelation.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ExpandedRelation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (treeTypeCase_ == TreeTypeOneofCase.Intermediate) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Intermediate);
      }
      if (treeTypeCase_ == TreeTypeOneofCase.Leaf) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Leaf);
      }
      if (expandedObject_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ExpandedObject);
      }
      if (ExpandedRelation.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ExpandedRelation);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PermissionRelationshipTree other) {
      if (other == null) {
        return;
      }
      if (other.expandedObject_ != null) {
        if (expandedObject_ == null) {
          ExpandedObject = new global::Authzed.Api.V1.ObjectReference();
        }
        ExpandedObject.MergeFrom(other.ExpandedObject);
      }
      if (other.ExpandedRelation.Length != 0) {
        ExpandedRelation = other.ExpandedRelation;
      }
      switch (other.TreeTypeCase) {
        case TreeTypeOneofCase.Intermediate:
          if (Intermediate == null) {
            Intermediate = new global::Authzed.Api.V1.AlgebraicSubjectSet();
          }
          Intermediate.MergeFrom(other.Intermediate);
          break;
        case TreeTypeOneofCase.Leaf:
          if (Leaf == null) {
            Leaf = new global::Authzed.Api.V1.DirectSubjectSet();
          }
          Leaf.MergeFrom(other.Leaf);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Authzed.Api.V1.AlgebraicSubjectSet subBuilder = new global::Authzed.Api.V1.AlgebraicSubjectSet();
            if (treeTypeCase_ == TreeTypeOneofCase.Intermediate) {
              subBuilder.MergeFrom(Intermediate);
            }
            input.ReadMessage(subBuilder);
            Intermediate = subBuilder;
            break;
          }
          case 18: {
            global::Authzed.Api.V1.DirectSubjectSet subBuilder = new global::Authzed.Api.V1.DirectSubjectSet();
            if (treeTypeCase_ == TreeTypeOneofCase.Leaf) {
              subBuilder.MergeFrom(Leaf);
            }
            input.ReadMessage(subBuilder);
            Leaf = subBuilder;
            break;
          }
          case 26: {
            if (expandedObject_ == null) {
              ExpandedObject = new global::Authzed.Api.V1.ObjectReference();
            }
            input.ReadMessage(ExpandedObject);
            break;
          }
          case 34: {
            ExpandedRelation = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Authzed.Api.V1.AlgebraicSubjectSet subBuilder = new global::Authzed.Api.V1.AlgebraicSubjectSet();
            if (treeTypeCase_ == TreeTypeOneofCase.Intermediate) {
              subBuilder.MergeFrom(Intermediate);
            }
            input.ReadMessage(subBuilder);
            Intermediate = subBuilder;
            break;
          }
          case 18: {
            global::Authzed.Api.V1.DirectSubjectSet subBuilder = new global::Authzed.Api.V1.DirectSubjectSet();
            if (treeTypeCase_ == TreeTypeOneofCase.Leaf) {
              subBuilder.MergeFrom(Leaf);
            }
            input.ReadMessage(subBuilder);
            Leaf = subBuilder;
            break;
          }
          case 26: {
            if (expandedObject_ == null) {
              ExpandedObject = new global::Authzed.Api.V1.ObjectReference();
            }
            input.ReadMessage(ExpandedObject);
            break;
          }
          case 34: {
            ExpandedRelation = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// AlgebraicSubjectSet is a subject set which is computed based on applying the
  /// specified operation to the operands according to the algebra of sets.
  ///
  /// UNION is a logical set containing the subject members from all operands.
  ///
  /// INTERSECTION is a logical set containing only the subject members which are
  /// present in all operands.
  ///
  /// EXCLUSION is a logical set containing only the subject members which are
  /// present in the first operand, and none of the other operands.
  /// </summary>
  public sealed partial class AlgebraicSubjectSet : pb::IMessage<AlgebraicSubjectSet>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AlgebraicSubjectSet> _parser = new pb::MessageParser<AlgebraicSubjectSet>(() => new AlgebraicSubjectSet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AlgebraicSubjectSet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Authzed.Api.V1.CoreReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AlgebraicSubjectSet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AlgebraicSubjectSet(AlgebraicSubjectSet other) : this() {
      operation_ = other.operation_;
      children_ = other.children_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AlgebraicSubjectSet Clone() {
      return new AlgebraicSubjectSet(this);
    }

    /// <summary>Field number for the "operation" field.</summary>
    public const int OperationFieldNumber = 1;
    private global::Authzed.Api.V1.AlgebraicSubjectSet.Types.Operation operation_ = global::Authzed.Api.V1.AlgebraicSubjectSet.Types.Operation.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Authzed.Api.V1.AlgebraicSubjectSet.Types.Operation Operation {
      get { return operation_; }
      set {
        operation_ = value;
      }
    }

    /// <summary>Field number for the "children" field.</summary>
    public const int ChildrenFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Authzed.Api.V1.PermissionRelationshipTree> _repeated_children_codec
        = pb::FieldCodec.ForMessage(18, global::Authzed.Api.V1.PermissionRelationshipTree.Parser);
    private readonly pbc::RepeatedField<global::Authzed.Api.V1.PermissionRelationshipTree> children_ = new pbc::RepeatedField<global::Authzed.Api.V1.PermissionRelationshipTree>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Authzed.Api.V1.PermissionRelationshipTree> Children {
      get { return children_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AlgebraicSubjectSet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AlgebraicSubjectSet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Operation != other.Operation) return false;
      if(!children_.Equals(other.children_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Operation != global::Authzed.Api.V1.AlgebraicSubjectSet.Types.Operation.Unspecified) hash ^= Operation.GetHashCode();
      hash ^= children_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Operation != global::Authzed.Api.V1.AlgebraicSubjectSet.Types.Operation.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Operation);
      }
      children_.WriteTo(output, _repeated_children_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Operation != global::Authzed.Api.V1.AlgebraicSubjectSet.Types.Operation.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Operation);
      }
      children_.WriteTo(ref output, _repeated_children_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Operation != global::Authzed.Api.V1.AlgebraicSubjectSet.Types.Operation.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Operation);
      }
      size += children_.CalculateSize(_repeated_children_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AlgebraicSubjectSet other) {
      if (other == null) {
        return;
      }
      if (other.Operation != global::Authzed.Api.V1.AlgebraicSubjectSet.Types.Operation.Unspecified) {
        Operation = other.Operation;
      }
      children_.Add(other.children_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Operation = (global::Authzed.Api.V1.AlgebraicSubjectSet.Types.Operation) input.ReadEnum();
            break;
          }
          case 18: {
            children_.AddEntriesFrom(input, _repeated_children_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Operation = (global::Authzed.Api.V1.AlgebraicSubjectSet.Types.Operation) input.ReadEnum();
            break;
          }
          case 18: {
            children_.AddEntriesFrom(ref input, _repeated_children_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the AlgebraicSubjectSet message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Operation {
        [pbr::OriginalName("OPERATION_UNSPECIFIED")] Unspecified = 0,
        [pbr::OriginalName("OPERATION_UNION")] Union = 1,
        [pbr::OriginalName("OPERATION_INTERSECTION")] Intersection = 2,
        [pbr::OriginalName("OPERATION_EXCLUSION")] Exclusion = 3,
      }

    }
    #endregion

  }

  /// <summary>
  /// DirectSubjectSet is a subject set which is simply a collection of subjects.
  /// </summary>
  public sealed partial class DirectSubjectSet : pb::IMessage<DirectSubjectSet>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DirectSubjectSet> _parser = new pb::MessageParser<DirectSubjectSet>(() => new DirectSubjectSet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DirectSubjectSet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Authzed.Api.V1.CoreReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DirectSubjectSet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DirectSubjectSet(DirectSubjectSet other) : this() {
      subjects_ = other.subjects_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DirectSubjectSet Clone() {
      return new DirectSubjectSet(this);
    }

    /// <summary>Field number for the "subjects" field.</summary>
    public const int SubjectsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Authzed.Api.V1.SubjectReference> _repeated_subjects_codec
        = pb::FieldCodec.ForMessage(10, global::Authzed.Api.V1.SubjectReference.Parser);
    private readonly pbc::RepeatedField<global::Authzed.Api.V1.SubjectReference> subjects_ = new pbc::RepeatedField<global::Authzed.Api.V1.SubjectReference>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Authzed.Api.V1.SubjectReference> Subjects {
      get { return subjects_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DirectSubjectSet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DirectSubjectSet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!subjects_.Equals(other.subjects_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= subjects_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      subjects_.WriteTo(output, _repeated_subjects_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      subjects_.WriteTo(ref output, _repeated_subjects_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += subjects_.CalculateSize(_repeated_subjects_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DirectSubjectSet other) {
      if (other == null) {
        return;
      }
      subjects_.Add(other.subjects_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            subjects_.AddEntriesFrom(input, _repeated_subjects_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            subjects_.AddEntriesFrom(ref input, _repeated_subjects_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
